//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace Smrf.NodeXL.ExcelTemplate {
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(7)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class Sheet4 : Microsoft.Office.Tools.Excel.WorksheetBase {
        
        internal Microsoft.Office.Tools.Excel.NamedRange ValidEdgeVisibilities;
        
        internal Microsoft.Office.Tools.Excel.NamedRange ValidVertexShapes;
        
        internal Microsoft.Office.Tools.Excel.NamedRange ValidVertexVisibilities;
        
        internal Microsoft.Office.Tools.Excel.NamedRange ValidBooleansDefaultFalse;
        
        internal Microsoft.Office.Tools.Excel.ListObject PerWorkbookSettings;
        
        internal Microsoft.Office.Tools.Excel.ListObject DynamicFilterSettings;
        
        internal Microsoft.Office.Tools.Excel.Chart DynamicFilterHistogram;
        
        internal Microsoft.Office.Tools.Excel.NamedRange ValidEdgeStyles;
        
        internal Microsoft.Office.Tools.Excel.NamedRange ValidGroupShapes;
        
        internal Microsoft.Office.Tools.Excel.NamedRange ValidGroupVisibilities;
        
        internal Microsoft.Office.Tools.Excel.NamedRange ValidVertexLabelPositions;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Sheet4(global::Microsoft.Office.Tools.Excel.Factory factory, global::System.IServiceProvider serviceProvider) : 
                base(factory, serviceProvider, "Sheet4", "Sheet4") {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            Globals.Sheet4 = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
            this.ValidEdgeVisibilities.BeginInit();
            this.ValidVertexShapes.BeginInit();
            this.ValidVertexVisibilities.BeginInit();
            this.ValidBooleansDefaultFalse.BeginInit();
            this.PerWorkbookSettings.BeginInit();
            this.DynamicFilterSettings.BeginInit();
            this.DynamicFilterHistogram.BeginInit();
            this.ValidEdgeStyles.BeginInit();
            this.ValidGroupShapes.BeginInit();
            this.ValidGroupVisibilities.BeginInit();
            this.ValidVertexLabelPositions.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.ValidVertexLabelPositions.EndInit();
            this.ValidGroupVisibilities.EndInit();
            this.ValidGroupShapes.EndInit();
            this.ValidEdgeStyles.EndInit();
            this.DynamicFilterHistogram.EndInit();
            this.DynamicFilterSettings.EndInit();
            this.PerWorkbookSettings.EndInit();
            this.ValidBooleansDefaultFalse.EndInit();
            this.ValidVertexVisibilities.EndInit();
            this.ValidVertexShapes.EndInit();
            this.ValidEdgeVisibilities.EndInit();
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.ValidEdgeVisibilities = Globals.Factory.CreateNamedRange(null, null, "ValidEdgeVisibilities", "ValidEdgeVisibilities", this);
            this.ValidVertexShapes = Globals.Factory.CreateNamedRange(null, null, "ValidVertexShapes", "ValidVertexShapes", this);
            this.ValidVertexVisibilities = Globals.Factory.CreateNamedRange(null, null, "ValidVertexVisibilities", "ValidVertexVisibilities", this);
            this.ValidBooleansDefaultFalse = Globals.Factory.CreateNamedRange(null, null, "ValidBooleansDefaultFalse", "ValidBooleansDefaultFalse", this);
            this.PerWorkbookSettings = Globals.Factory.CreateListObject(null, null, "Sheet4:PerWorkbookSettings", "PerWorkbookSettings", this);
            this.DynamicFilterSettings = Globals.Factory.CreateListObject(null, null, "Sheet4:DynamicFilterSettings", "DynamicFilterSettings", this);
            this.DynamicFilterHistogram = Globals.Factory.CreateChart(null, null, "Sheet4:DynamicFilterHistogram", "DynamicFilterHistogram", this);
            this.ValidEdgeStyles = Globals.Factory.CreateNamedRange(null, null, "ValidEdgeStyles", "ValidEdgeStyles", this);
            this.ValidGroupShapes = Globals.Factory.CreateNamedRange(null, null, "ValidGroupShapes", "ValidGroupShapes", this);
            this.ValidGroupVisibilities = Globals.Factory.CreateNamedRange(null, null, "ValidGroupVisibilities", "ValidGroupVisibilities", this);
            this.ValidVertexLabelPositions = Globals.Factory.CreateNamedRange(null, null, "ValidVertexLabelPositions", "ValidVertexLabelPositions", this);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
            ((System.ComponentModel.ISupportInitialize)(this.ValidEdgeVisibilities)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ValidVertexShapes)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ValidVertexVisibilities)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ValidBooleansDefaultFalse)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.PerWorkbookSettings)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.DynamicFilterSettings)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ValidEdgeVisibilities)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ValidVertexShapes)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ValidVertexVisibilities)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ValidBooleansDefaultFalse)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.PerWorkbookSettings)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.DynamicFilterSettings)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this)).EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void OnShutdown() {
            this.ValidVertexLabelPositions.Dispose();
            this.ValidGroupVisibilities.Dispose();
            this.ValidGroupShapes.Dispose();
            this.ValidEdgeStyles.Dispose();
            this.DynamicFilterHistogram.Dispose();
            this.DynamicFilterSettings.Dispose();
            this.PerWorkbookSettings.Dispose();
            this.ValidBooleansDefaultFalse.Dispose();
            this.ValidVertexVisibilities.Dispose();
            this.ValidVertexShapes.Dispose();
            this.ValidEdgeVisibilities.Dispose();
            base.OnShutdown();
        }
    }
    
    internal sealed partial class Globals {
        
        private static Sheet4 _Sheet4;
        
        internal static Sheet4 Sheet4 {
            get {
                return _Sheet4;
            }
            set {
                if ((_Sheet4 == null)) {
                    _Sheet4 = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
    }
}
