//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace Smrf.NodeXL.ExcelTemplate {
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(6)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class Sheet7 : Microsoft.Office.Tools.Excel.WorksheetBase {
        
        internal Microsoft.Office.Tools.Excel.ListObject OverallMetrics;
        
        internal Microsoft.Office.Tools.Excel.Chart DegreeHistogram;
        
        internal Microsoft.Office.Tools.Excel.Chart InDegreeHistogram;
        
        internal Microsoft.Office.Tools.Excel.Chart OutDegreeHistogram;
        
        internal Microsoft.Office.Tools.Excel.Chart BetweennessCentralityHistogram;
        
        internal Microsoft.Office.Tools.Excel.Chart ClosenessCentralityHistogram;
        
        internal Microsoft.Office.Tools.Excel.Chart EigenvectorCentralityHistogram;
        
        internal Microsoft.Office.Tools.Excel.Chart ClusteringCoefficientHistogram;
        
        internal Microsoft.Office.Tools.Excel.ListObject HistogramBins;
        
        internal Microsoft.Office.Tools.Excel.ListObject HistogramProperties;
        
        internal Microsoft.Office.Tools.Excel.ListObject OverallReadabilityMetrics;
        
        internal Microsoft.Office.Tools.Excel.NamedRange BinDivisor;
        
        internal Microsoft.Office.Tools.Excel.NamedRange DynamicFilterForceCalculationRange;
        
        internal Microsoft.Office.Tools.Excel.NamedRange DynamicFilterSourceColumnRange;
        
        internal Microsoft.Office.Tools.Excel.NamedRange NoMetricMessage;
        
        internal Microsoft.Office.Tools.Excel.NamedRange NotAvailable;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Sheet7(global::Microsoft.Office.Tools.Excel.Factory factory, global::System.IServiceProvider serviceProvider) : 
                base(factory, serviceProvider, "Sheet7", "Sheet7") {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            Globals.Sheet7 = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
            this.OverallMetrics.BeginInit();
            this.DegreeHistogram.BeginInit();
            this.InDegreeHistogram.BeginInit();
            this.OutDegreeHistogram.BeginInit();
            this.BetweennessCentralityHistogram.BeginInit();
            this.ClosenessCentralityHistogram.BeginInit();
            this.EigenvectorCentralityHistogram.BeginInit();
            this.ClusteringCoefficientHistogram.BeginInit();
            this.HistogramBins.BeginInit();
            this.HistogramProperties.BeginInit();
            this.OverallReadabilityMetrics.BeginInit();
            this.BinDivisor.BeginInit();
            this.DynamicFilterForceCalculationRange.BeginInit();
            this.DynamicFilterSourceColumnRange.BeginInit();
            this.NoMetricMessage.BeginInit();
            this.NotAvailable.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.NotAvailable.EndInit();
            this.NoMetricMessage.EndInit();
            this.DynamicFilterSourceColumnRange.EndInit();
            this.DynamicFilterForceCalculationRange.EndInit();
            this.BinDivisor.EndInit();
            this.OverallReadabilityMetrics.EndInit();
            this.HistogramProperties.EndInit();
            this.HistogramBins.EndInit();
            this.ClusteringCoefficientHistogram.EndInit();
            this.EigenvectorCentralityHistogram.EndInit();
            this.ClosenessCentralityHistogram.EndInit();
            this.BetweennessCentralityHistogram.EndInit();
            this.OutDegreeHistogram.EndInit();
            this.InDegreeHistogram.EndInit();
            this.DegreeHistogram.EndInit();
            this.OverallMetrics.EndInit();
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.OverallMetrics = Globals.Factory.CreateListObject(null, null, "Sheet7:OverallMetrics", "OverallMetrics", this);
            this.DegreeHistogram = Globals.Factory.CreateChart(null, null, "Sheet7:DegreeHistogram", "DegreeHistogram", this);
            this.InDegreeHistogram = Globals.Factory.CreateChart(null, null, "Sheet7:InDegreeHistogram", "InDegreeHistogram", this);
            this.OutDegreeHistogram = Globals.Factory.CreateChart(null, null, "Sheet7:OutDegreeHistogram", "OutDegreeHistogram", this);
            this.BetweennessCentralityHistogram = Globals.Factory.CreateChart(null, null, "Sheet7:BetweennessCentralityHistogram", "BetweennessCentralityHistogram", this);
            this.ClosenessCentralityHistogram = Globals.Factory.CreateChart(null, null, "Sheet7:ClosenessCentralityHistogram", "ClosenessCentralityHistogram", this);
            this.EigenvectorCentralityHistogram = Globals.Factory.CreateChart(null, null, "Sheet7:EigenvectorCentralityHistogram", "EigenvectorCentralityHistogram", this);
            this.ClusteringCoefficientHistogram = Globals.Factory.CreateChart(null, null, "Sheet7:ClusteringCoefficientHistogram", "ClusteringCoefficientHistogram", this);
            this.HistogramBins = Globals.Factory.CreateListObject(null, null, "Sheet7:HistogramBins", "HistogramBins", this);
            this.HistogramProperties = Globals.Factory.CreateListObject(null, null, "Sheet7:HistogramProperties", "HistogramProperties", this);
            this.OverallReadabilityMetrics = Globals.Factory.CreateListObject(null, null, "Sheet7:OverallReadabilityMetrics", "OverallReadabilityMetrics", this);
            this.BinDivisor = Globals.Factory.CreateNamedRange(null, null, "BinDivisor", "BinDivisor", this);
            this.DynamicFilterForceCalculationRange = Globals.Factory.CreateNamedRange(null, null, "DynamicFilterForceCalculationRange", "DynamicFilterForceCalculationRange", this);
            this.DynamicFilterSourceColumnRange = Globals.Factory.CreateNamedRange(null, null, "DynamicFilterSourceColumnRange", "DynamicFilterSourceColumnRange", this);
            this.NoMetricMessage = Globals.Factory.CreateNamedRange(null, null, "NoMetricMessage", "NoMetricMessage", this);
            this.NotAvailable = Globals.Factory.CreateNamedRange(null, null, "NotAvailable", "NotAvailable", this);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void OnShutdown() {
            this.NotAvailable.Dispose();
            this.NoMetricMessage.Dispose();
            this.DynamicFilterSourceColumnRange.Dispose();
            this.DynamicFilterForceCalculationRange.Dispose();
            this.BinDivisor.Dispose();
            this.OverallReadabilityMetrics.Dispose();
            this.HistogramProperties.Dispose();
            this.HistogramBins.Dispose();
            this.ClusteringCoefficientHistogram.Dispose();
            this.EigenvectorCentralityHistogram.Dispose();
            this.ClosenessCentralityHistogram.Dispose();
            this.BetweennessCentralityHistogram.Dispose();
            this.OutDegreeHistogram.Dispose();
            this.InDegreeHistogram.Dispose();
            this.DegreeHistogram.Dispose();
            this.OverallMetrics.Dispose();
            base.OnShutdown();
        }
    }
    
    internal sealed partial class Globals {
        
        private static Sheet7 _Sheet7;
        
        internal static Sheet7 Sheet7 {
            get {
                return _Sheet7;
            }
            set {
                if ((_Sheet7 == null)) {
                    _Sheet7 = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
    }
}
