//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591  // "Missing XML comment..."

namespace Smrf.GraphServer.WcfService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/Smrf.GraphServer.WcfService")]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool BoolValueField;
        
        private string StringValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue
        {
            get
            {
                return this.BoolValueField;
            }
            set
            {
                this.BoolValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue
        {
            get
            {
                return this.StringValueField;
            }
            set
            {
                this.StringValueField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IGraphService")]
public interface IGraphService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGraphService/GetTwitterSearchNetworkAsZippedGraphML", ReplyAction="http://tempuri.org/IGraphService/GetTwitterSearchNetworkAsZippedGraphMLResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/IGraphService/GetTwitterSearchNetworkAsZippedGraphMLStringFaul" +
        "t", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
    byte[] GetTwitterSearchNetworkAsZippedGraphML(string searchTerm, System.DateTime minimumStatusDateUtc, System.DateTime maximumStatusDateUtc, bool expandStatusUrls, string graphServerUserName, string graphServerPassword);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGraphService/GetData", ReplyAction="http://tempuri.org/IGraphService/GetDataResponse")]
    string GetData(int value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGraphService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IGraphService/GetDataUsingDataContractResponse")]
    Smrf.GraphServer.WcfService.CompositeType GetDataUsingDataContract(Smrf.GraphServer.WcfService.CompositeType composite);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IGraphServiceChannel : IGraphService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class GraphServiceClient : System.ServiceModel.ClientBase<IGraphService>, IGraphService
{
    
    public GraphServiceClient()
    {
    }
    
    public GraphServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public GraphServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public GraphServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public GraphServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public byte[] GetTwitterSearchNetworkAsZippedGraphML(string searchTerm, System.DateTime minimumStatusDateUtc, System.DateTime maximumStatusDateUtc, bool expandStatusUrls, string graphServerUserName, string graphServerPassword)
    {
        return base.Channel.GetTwitterSearchNetworkAsZippedGraphML(searchTerm, minimumStatusDateUtc, maximumStatusDateUtc, expandStatusUrls, graphServerUserName, graphServerPassword);
    }
    
    public string GetData(int value)
    {
        return base.Channel.GetData(value);
    }
    
    public Smrf.GraphServer.WcfService.CompositeType GetDataUsingDataContract(Smrf.GraphServer.WcfService.CompositeType composite)
    {
        return base.Channel.GetDataUsingDataContract(composite);
    }
}
